
spring:
    application:
    name: BoardByJDBC

    datasource:
        url: jdbc:mysql://localhost:3306/librarydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
        username: root
        password: root1234
        driver-class-name: com.mysql.cj.jdbc.Driver